# mail-server
---
apiVersion: v1
data:
  application.properties: |-
    app.id=common-mailserver-001
kind: ConfigMap
metadata:
  name: mail-server
---
apiVersion: v1
data:
  server.properties: |-
    env=PRO
kind: ConfigMap
metadata:
  name: mail-server-apollo
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mail-server
  labels:
    app: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
      - name: mail-server
        image: docker-registry.cluster.dfwsgroup.cn/library/mail-server:1.0.0
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appconfig
          mountPath: /config
        - name: appconfig-apollo
          mountPath: /opt/settings
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
      volumes:
      - name: appconfig
        configMap:
          name: mail-server
      - name: appconfig-apollo
        configMap:
          name: mail-server-apollo
---
